# Generated by Django 3.2.13 on 2022-05-14 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webevent',
            name='scout_id',
            field=models.CharField(blank=True, help_text='The first-http-request tag we set on handshake', max_length=1000, null=True),
        ),
    ]
